AWSTemplateFormatVersion: 2010-09-09

Parameters:
  DomainID:
    Type: String
    Default: <ADD YOUR STUDIO DOMAIN ID HERE>
  ImageName:
    Type: String
    Default: tf25
  ImageRoleArn:
    Type: String
    Default: <ADD THE IMAGE ROLE ARN HERE>

Resources:
  #================================================================================
  # CODEPIPELINE
  #================================================================================
  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Ref ImageName
      RoleArn: !GetAtt CodePipelineRole.Arn
      ArtifactStore:
        Location: !Ref PipelineArtifactBucket
        Type: S3
      RestartExecutionOnUpdate: True
      Stages:
        - Name: Source
          Actions:
            - InputArtifacts: [ ]
              Name: Source
              ActionTypeId:
                Category: Source
                Owner: AWS
                Version: 1
                Provider: CodeCommit
              Configuration:
                RepositoryName: !GetAtt CodeRepository.Name
                BranchName: master
              OutputArtifacts:
                - Name: CFNSource
              RunOrder: 1

        - Name: Build
          Actions:
            - Name: Build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              Configuration:
                ProjectName: !Ref CodeBuild
              InputArtifacts:
                - Name: CFNSource
              RunOrder: 1
  #================================================================================
  # IAM
  #================================================================================
  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:*
                Resource: !Sub ${PipelineArtifactBucket.Arn}/*
              - Effect: Allow
                Action:
                  - codecommit:*
                Resource: !GetAtt CodeRepository.Arn
              - Effect: Allow
                Action:
                  - codebuild:*
                Resource: !GetAtt CodeBuild.Arn

  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          Effect: Allow
          Principal:
            Service: codebuild.amazonaws.com
          Action: sts:AssumeRole
      Policies:
        - PolicyName: policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:*
                Resource: !Sub ${PipelineArtifactBucket.Arn}/*
              - Effect: Allow
                Action:
                  - ecr:*
                Resource: !Sub arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/${ImageName}
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                Resource: '*'
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:DescribeLogGroups
                  - logs:DescribeLogStreams
                  - logs:PutLogEvents
                  - logs:GetLogEvents
                  - logs:FilterLogEvents
                Resource: '*'
              - Effect: Allow
                Action:
                  - sagemaker:UpdateDomain
                  - sagemaker:CreateImage
                  - sagemaker:CreateImageVersion
                  - sagemaker:UpdateImage
                  - sagemaker:UpdateAppImageConfig
                  - sagemaker:DeleteImage
                  - sagemaker:DeleteImageVersion
                  - sagemaker:CreateAppImageConfig
                  - sagemaker:DeleteAppImageConfig
                Resource: !Sub arn:aws:sagemaker:${AWS::Region}:${AWS::AccountId}:*
  #================================================================================
  # CODEBUILD
  #================================================================================
  CodeBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Ref ImageName
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_LARGE
        Image: aws/codebuild/standard:6.0
        Type: LINUX_CONTAINER
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: DOMAIN_ID
            Value: !Ref DomainID
          - Name: IMAGE_NAME
            Value: !Ref ImageName
          - Name: ACCOUNT_ID
            Value: !Ref AWS::AccountId
          - Name: REGION
            Value: !Ref AWS::Region
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec.yaml
  #================================================================================
  # S3
  #================================================================================
  PipelineArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${ImageName}-studio-image-${AWS::AccountId}
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
  #================================================================================
  # CODECOMMIT
  #================================================================================
  CodeRepository:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: !Ref ImageName
  #================================================================================
  # STUDIO IMAGE
  #================================================================================
  StudioImage:
    Type: AWS::SageMaker::Image
    Properties:
      ImageDescription: Tensorflow 2.5.0 in Studio
      ImageDisplayName: !Ref ImageName
      ImageName: !Ref ImageName
      ImageRoleArn: !Ref ImageRoleArn
